/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopg1;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.CLOSED_OPTION;
import javax.swing.JTextField;
import static oopg1.Fire.tree;

/**
 *
 * @author Mostheblu
 */
public class App extends javax.swing.JFrame {

    static Forest f;
    Fire fire;
    String help;
    String probcatch;
    String probtree;
    String probburn;
    boolean haveprob = true;

    public App() {
        initComponents();
        f = new Forest(23);
        fire = new Fire(f, 23);
        setVisible(true);
        add(f);
        this.setTitle("Spread of Fire");
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jTextField2.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextField3.setVisible(false);
        jRadioButton1.setSelected(true);
        jButton4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 0));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        jRadioButton1.setText("Auto  On");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        jRadioButton2.setText("Random ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 14)); // NOI18N
        jLabel1.setText("Forest Size");

        jLabel2.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel2.setText("Input probability ");

        jLabel3.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel3.setText("CatchFire(0.00-1.00)");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel4.setText("Step = 0");

        jLabel5.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel5.setText("Tree(0.00-1.00)");

        jLabel6.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel6.setText("Input probability ");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel7.setText("Input probability");

        jLabel8.setFont(new java.awt.Font("Bauhaus 93", 0, 11)); // NOI18N
        jLabel8.setText("Burn (0.00-1.00)");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("HELP ?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 51));
        jButton4.setText("Set");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 568, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jLabel3)
                                            .addComponent(jRadioButton2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // Auto mode 
        if (jRadioButton1.isSelected()) {
            jButton1.setText("Start");
            jRadioButton1.setText("Auto ON");

        } else {

            jRadioButton1.setText("Auto OFF");
            jButton1.setText("Step");
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        Object sizeChoice = jComboBox1.getSelectedItem();
        if (sizeChoice.equals("Small")) {
            fire.setNumberTree(23);
            f.setSizeTree(23);
            fire = new Fire(f, fire.getNumberTree());
            fire.initGrid();

        } else if (sizeChoice.equals("Medium")) {
            fire.setNumberTree(41);
            f.setSizeTree(13);
            fire = new Fire(f, fire.getNumberTree());
            fire.initGrid();

        } else if (sizeChoice.equals("Large")) {
            fire.setNumberTree(69);
            f.setSizeTree(8);
            fire = new Fire(f, fire.getNumberTree());
            fire.initGrid();
        } else {
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Start button

        Thread t = new Thread(new Runnable() {
            public void run() {

                if (jRadioButton1.isSelected()) {
                    try {

                        while (!fire.isFinish()) {
                            Thread.sleep(100);
                            fire.setprobCatch(Float.parseFloat(jTextField1.getText()));
                            haveprob = true;
                            while (Float.parseFloat(jTextField1.getText()) < 0 || Float.parseFloat(jTextField1.getText()) > 1.00) {
                                probcatch = JOptionPane.showInputDialog(null, "please input probability of catchfire only 0.00-1.00", "Warning",
                                        JOptionPane.WARNING_MESSAGE);
                                fire.setprobCatch(Float.parseFloat(probcatch));
                                jTextField1.setText(probcatch);
                            }

                            fire.search();
                            f.update(tree);
                            fire.cnt++;
                            fire.reset();
                            if (!fire.isFinish()) {
                                jLabel4.setText("Step = " + String.valueOf(fire.getCnt()));
                            }

                        }
                    } catch (Exception e) {

                    }
                    f.repaint();

                } else if (jRadioButton1.isSelected() == false && jRadioButton2.isSelected()) { //Random on & Auto off
                    try {
                        fire.setprobCatch(Float.parseFloat(jTextField1.getText()));
                        while (Float.parseFloat(jTextField1.getText()) < 0 || Float.parseFloat(jTextField1.getText()) > 1.00) {
                            probcatch = JOptionPane.showInputDialog(null, "please input probability of catch only 0.00-1.00", "Warning",
                                    JOptionPane.WARNING_MESSAGE);
                            fire.setprobCatch(Float.parseFloat(probcatch));
                            jTextField1.setText(probcatch);
                        }
                        fire.run();

                        repaint();

                    } catch (Exception e) {
                    }
                    if (!fire.isFinish()) {
                        jLabel4.setText("Step = " + String.valueOf(fire.getCnt()));
                    }

                }

                if (jRadioButton1.isSelected() && !jRadioButton2.isSelected()) {
                    try {
                        while (!fire.isFinish()) {
                            Thread.sleep(100);
                            fire.setprobCatch(Float.parseFloat(jTextField1.getText()));
                            while (Float.parseFloat(jTextField1.getText()) < 0 || Float.parseFloat(jTextField1.getText()) > 1.00) {
                                probcatch = JOptionPane.showInputDialog(null, "\"please input probability of catchfire only 0.00-1.00", "Warning",
                                        JOptionPane.WARNING_MESSAGE);
                                fire.setprobCatch(Float.parseFloat(probcatch));
                                jTextField1.setText(probcatch);
                            }

                            fire.search();
                            f.update(tree);
                            fire.cnt++;
                            fire.reset();
                            if (!fire.isFinish()) {
                                jLabel4.setText("Step = " + String.valueOf(fire.getCnt()));
                            }

                        }
                    } catch (Exception e) {
                    }
                    f.repaint();

                }

                if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) {
                    try {
                        fire.run();
                        fire.setprobCatch(Float.parseFloat(jTextField1.getText()));
                        while (Float.parseFloat(jTextField1.getText()) < 0 || Float.parseFloat(jTextField1.getText()) > 1.00) {
                            probcatch = JOptionPane.showInputDialog(null, "please input probability of catch only 0.00-1.00", "Warning",
                                    JOptionPane.WARNING_MESSAGE);
                            fire.setprobCatch(Float.parseFloat(probcatch));
                            jTextField1.setText(probcatch);
                        }
                        repaint();

                    } catch (Exception e) {

                    }
                    if (!fire.isFinish()) {
                        jLabel4.setText("Step = " + String.valueOf(fire.getCnt()));
                    }

                }
            }
        }
        );

        t.start();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Reset button
        jTextField1.setText(null);
        if (jRadioButton2.isSelected()) {

            jTextField2.setText("1");
            jTextField3.setText("0");
            fire.setpropTree(Float.parseFloat(jTextField2.getText()));
            fire.setpropBurn(Float.parseFloat(jTextField3.getText()));
            jTextField2.setText(null);
            jTextField3.setText(null);
            fire.initGrid();
            fire.setCnt(0);
            jLabel4.setText("Step = 0");
            f.repaint();
        } else {
            fire.initGrid();
            fire.setCnt(0);
            jLabel4.setText("Step = 0");

            f.repaint();
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // Random
        if (!jRadioButton2.isSelected()) {
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jTextField2.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jTextField3.setVisible(false);
            jButton4.setVisible(false);
        } else {
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jTextField2.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jTextField3.setVisible(true);
            jButton4.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null, "Step 1 : User can select size of Forest (small, medium,large) \n"
                + "Step 2 : User can input the probability of Catch Fire (input between 0.00 and 1.00) \n"
                + "Step 3 : If you want program run automatically choose Auto On , if want program run step by step choose Auto Off\n"
                + "Step 4 : If user click \"random\" button the program will show the interface \"probtree\" and \"probburn\".\n That allowed users input probability between 0.00 to 1.00\n"
                + "Step 5 : After use input probtree and probburn ,user must click set button to simulate forest.\n"
                + "Step 6 : User can click start button to start burning, after user input probability and select mode (Auto on,off or Random)\n"
                + "Step 7 : User can restart the application by click \"Reset Button\".", "Help",
                JOptionPane.WARNING_MESSAGE);
        this.setTitle("Help & Menual");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jRadioButton2.isSelected()) {
            try {
                fire.setpropTree(Float.parseFloat(jTextField2.getText()));
                fire.setpropBurn(Float.parseFloat(jTextField3.getText()));
                while (Float.parseFloat(jTextField2.getText()) < 0 || Float.parseFloat(jTextField2.getText()) > 1.00) {
                    probtree = JOptionPane.showInputDialog(null, "please input probability of tree only 0.00-1.00", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                    fire.setpropTree(Float.parseFloat(probtree));
                    jTextField2.setText(probtree);
                }
                while (Float.parseFloat(jTextField3.getText()) < 0 || Float.parseFloat(jTextField3.getText()) > 1.00) {
                    probburn = JOptionPane.showInputDialog(null, "please input probability of burn only 0.00-1.00", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                    fire.setpropBurn(Float.parseFloat(probburn));
                    jTextField3.setText(probburn);
                }

                fire.initGrid();

            } catch (Exception e) {
            }
        }
        f.repaint();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
